HW2 add main.js
KonstantinEw/TMS-homeworks pull request #1
Opened 2022-07-23 17:19 UTC by KonstantinEw

I added homework -2

2022-07-23 21:30 UTC, igorstasiuk requested changes

2022-07-23 21:30 UTC, igorstasiuk commented on main.js
> +    console.log(String(a)+String(b)+' '+c);
самое просто было сделать `${a}${b} ${c}`, через строковый литерал

2022-07-23 21:30 UTC, igorstasiuk commented on main.js
> +    console.log(`Variable:${firstVar} have type: ${typeof (firstVar)}`);
выведиться `Variable: 42 have type: number`, главный смысл название переменной самое первое

2022-07-23 21:30 UTC, igorstasiuk commented on main.js
> +    let ageLocal = prompt(`Введите Ваш возраст: `);
нет вывода в консоль

2022-07-23 21:30 UTC, igorstasiuk commented on main.js
> +    let cipher = codeWord1[2-1]+codeWord2[2-1]+codeWord3[2-1]+codeWord4[2-1]+codeWord5[2-1];
а зачем тут 2-1 ?

2022-07-24 16:17 UTC, KonstantinEw commented on main.js
> +    let cipher = codeWord1[2-1]+codeWord2[2-1]+codeWord3[2-1]+codeWord4[2-1]+codeWord5[2-1];
По условию 2й символ, а исчесления с 0 же, слишком буквально)

2022-07-24 19:12 UTC, igorstasiuk commented on main.js
> +    let cipher = codeWord1[2-1]+codeWord2[2-1]+codeWord3[2-1]+codeWord4[2-1]+codeWord5[2-1];
отсчет идет от 0, можно было указать просто 1, зачем делать 2-1 ?

2022-07-24 19:13 UTC, igorstasiuk requested changes

2022-07-24 19:13 UTC, igorstasiuk commented on main.js
> +    console.log(nameLocal,ageLocal);
"Привет {имя}, твой возраст - {возраст}"

2022-07-25 09:05 UTC, igorstasiuk approved these changes

2022-07-25 09:52 UTC, merged